# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
import './Common'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Create a new dev build"
  lane :dev do
    # increment_build_number(xcodeproj: "FoodieRN.xcodeproj")
    copy_env_for_build_type('dev')
    build_app(
      workspace: "./ios/FoodieRN.xcworkspace",
      scheme: "FoodieRN",
      export_method: "development"
    )
  end
end
